#!/usr/bin/env bash

echo "Searching for Docker image ..."
DOCKER_IMAGE_ID=$(docker images -q teacupx/chromium-armhf:latest | head -n 1)
echo "Found and using ${DOCKER_IMAGE_ID}"

docker run --rm --privileged \
 -e DISPLAY=unix$DISPLAY \
 -v chromium_home:/home \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v /dev:/dev -v /run:/run \
 -v /etc/machine-id:/etc/machine-id \
  ${DOCKER_IMAGE_ID} \
  ${@}

#LATEST_IMAGE_ID=$(docker ps -l -q | head -n 1)

#echo "Comitting changes to image ${LATEST_IMAGE_ID}"
#docker commit ${LATEST_IMAGE_ID} teacupx/chromium-armhf
