#!/usr/bin/env bash

echo "Set host IP for Pulseaudio"
addrip="$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')"

echo "Enabling XHost Forwarding"
xhost +local:docker

echo "Searching for Docker image ..."
DOCKER_IMAGE_ID=$(docker images -q hthiemann/chromium-armhf:latest | head -n 1)
echo "Found and using ${DOCKER_IMAGE_ID}"

docker run --rm --privileged \
 -e DISPLAY=unix$DISPLAY \
 -e PULSE_SERVER=tcp:${addrip}:4713 \
 -e PULSE_COOKIE_DATA=`pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*'` \
 -v chromium_home:/home \
 -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v /dev:/dev -v /run:/run \
 -v /etc/machine-id:/etc/machine-id \
 --ipc=host \
  ${DOCKER_IMAGE_ID}
